- name: "Data Science"
  icon: "area-chart"
  description: "Python | R | SQL | SPSS | Pandas | Numpy | Seaborn | Tensorflow | Keras | Scikit-Learn"

- name: "Software"
  icon: "laptop"
  description: "AWS | Git | Postman | Sentry | DataDog | Grafana | Docker"

- name: "Documentation"
  icon: "pencil-square-o"
  description: "JIRA | LaTeX | Google Workspace | MS Office Suite"

